CREATE TABLE amostras (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ectoparasitos bool NULL,
	fezes bool NULL,
	"local" bool NULL,
	outros varchar(255) NULL,
	pelo bool NULL,
	sangue bool NULL,
	swab bool NULL,
	CONSTRAINT amostras_pkey PRIMARY KEY (id)
);

CREATE TABLE biometrias (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	comprimento_da_cabeca float8 NULL,
	comprimento_da_cauda float8 NULL,
	comprimento_da_orelha float8 NULL,
	comprimento_do_clitoris float8 NULL,
	comprimento_do_penis float8 NULL,
	comprimento_escudo_cefalico float8 NULL,
	comprimento_escudo_escapular float8 NULL,
	comprimento_escudo_pelvico float8 NULL,
	comprimento_mao_sem_unha float8 NULL,
	comprimento_pe_sem_unha float8 NULL,
	comprimento_total float8 NULL,
	comprimento_unha_da_mao float8 NULL,
	comprimento_unha_do_pe float8 NULL,
	largura_base_penis float8 NULL,
	largura_da_cabeca float8 NULL,
	largura_da_cauda float8 NULL,
	largura_escudo_cefalico float8 NULL,
	largura_inter_lacrimal float8 NULL,
	largura_inter_orbital float8 NULL,
	largura_na_segunda_cinta float8 NULL,
	numero_de_cintas int4 NULL,
	padrao_escudo_cefalico varchar(255) NULL,
	semicircunferencia_escudo_escapular float8 NULL,
	semicircunferencia_escudo_pelvico float8 NULL,
	CONSTRAINT biometrias_pkey PRIMARY KEY (id)
);

CREATE TABLE dados_gerais (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	contato_do_responsavel varchar(255) NULL,
	data_captura timestamp(6) NULL,
	equipe_responsavel varchar(255) NULL,
	instituicao varchar(255) NULL,
	local_de_captura varchar(255) NULL,
	observacoes varchar(255) NULL,
	peso_do_tatu float8 NULL,
	CONSTRAINT dados_gerais_pkey PRIMARY KEY (id)
);

CREATE TABLE fichas_anestesicas (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	aplicacao time(6) NULL,
	inducao time(6) NULL,
	retorno time(6) NULL,
	tipo_anestesico_ou_dose varchar(255) NULL,
	via_de_administracao varchar(255) NULL,
	CONSTRAINT fichas_anestesicas_pkey PRIMARY KEY (id)
);

CREATE TABLE tatus (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	identificacao_animal varchar(255) NULL,
	numero_microchip int4 NULL,
	CONSTRAINT tatus_pkey PRIMARY KEY (id)
);

CREATE TABLE usuarios (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ativo bool NULL,
	email varchar(255) NULL,
	nome varchar(255) NULL,
	senha varchar(255) NULL,
	telefone varchar(255) NULL,
	CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);

CREATE TABLE capturas (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amostra_id int8 NULL,
	biometria_id int8 NULL,
	dados_gerais_id int8 NULL,
	ficha_anestesica_id int8 NULL,
	tatu_id int8 NULL,
	usuario_id int8 NULL,
	CONSTRAINT capturas_pkey PRIMARY KEY (id),
	CONSTRAINT uk61otfwasyfiegiof45blhqf5l UNIQUE (biometria_id),
	CONSTRAINT ukged1a264cl78xupjqc6nxyqio UNIQUE (dados_gerais_id),
	CONSTRAINT ukhiyhw202fuf2ik1ww1tpfulyx UNIQUE (ficha_anestesica_id),
	CONSTRAINT ukkcslphf2rlyvd3npl1if294m3 UNIQUE (amostra_id),
	CONSTRAINT fk1h33or122qekg8y9ia3lyj5w7 FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
	CONSTRAINT fk446uaujf20wdyb9jmmv8t19xl FOREIGN KEY (dados_gerais_id) REFERENCES dados_gerais(id),
	CONSTRAINT fkjfnpk1qaw41gk7ipv0u3qv5de FOREIGN KEY (ficha_anestesica_id) REFERENCES fichas_anestesicas(id),
	CONSTRAINT fkjpovio46fyd8rsue0eco8cws FOREIGN KEY (biometria_id) REFERENCES biometrias(id),
	CONSTRAINT fkoprni5rogc44gu95b48npkaif FOREIGN KEY (amostra_id) REFERENCES amostras(id),
	CONSTRAINT fkp8m0bcl818be97ld1ben3ang0 FOREIGN KEY (tatu_id) REFERENCES tatus(id)
);

CREATE TABLE parametros_fisiologicos (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	frequencia_cardiaca float8 NULL,
	frequencia_respiratoria float8 NULL,
	oximetria float8 NULL,
	temperatura float8 NULL,
	ficha_anestesica_id int8 NULL,
	CONSTRAINT parametros_fisiologicos_pkey PRIMARY KEY (id),
	CONSTRAINT fk7ey5wplpwp7836bk7vs05m69w FOREIGN KEY (ficha_anestesica_id) REFERENCES fichas_anestesicas(id)
);